"""Add on_menu to Category

Revision ID: 807d299dba89
Revises: 
Create Date: 2022-08-04 20:49:02.771846

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '807d299dba89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('on_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'on_menu')
    # ### end Alembic commands ###
