"""Add field active to Store model

Revision ID: 953c917e2bee
Revises: 807d299dba89
Create Date: 2022-08-04 20:56:15.968361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953c917e2bee'
down_revision = '807d299dba89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'active')
    # ### end Alembic commands ###
